### ISSUE TITLE
$modelRuleHelper in __construct() not found

### ISSUE THREAD

**Issue by sven-ahrens** [nunomaduro/larastan#1035]
- Larastan Version: 0.7.15
- `--level` used: 4

### Description
I'm using larastan for a while now and never had any issues. Today, I encountered an error in my gitlab pipeline which stated the following:

```
Note: Using configuration file /builds/x/x/phpstan.neon.
In Resolver.php line 447:
                                                                               
Service of type NunoMaduro\Larastan\Rules\ModelProperties\ModelPropertyRule : 
Service of type NunoMaduro\Larastan\Rules\ModelRuleHelper
needed by $modelRuleHelper in __construct() not found.
Did you add it to configuration file?
```

### phpstan.neon

_(This is a minified version. I excluded the ``ignorErrors`` and ``excludePaths`` here to make this as readable as possible)_

```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
parameters:
    level: 4
    ignoreErrors:
    paths:
        - app
    excludePaths:
        analyse:
```

I'm not sure what's the difference now, because a few days ago this worked just fine and I didn't update the ``phpstan.neon`` file.

Any help is appreciated. Thanks in advance!
