### ISSUE TITLE
Code analyze dies on Redis connection

### ISSUE THREAD

**Issue by sampsasaarela** [nunomaduro/larastan#1072]
- Larastan Version: 1.0.2
- `--level` used: 0-5

### Description

I have Laravel v8 and PHP 8 with predis. For some reason, code analyzes dies on every Redis connection call.

It just hangs for a while and then dies with the message: Killed

I tried to change facades on stub like here: https://github.com/nunomaduro/larastan/issues/907#issuecomment-895062233 but no changes. It "feels" like it tries actually connect and timeout, but there is no error and even if it does, I don't understand why it would try to do the actual connection. Any help if this is a possible bug in Larastan? Or what to check?

My config looks like this:
```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:

    paths:
        - app

    # The level 9 is the highest level
    level: 0

    ignoreErrors:
        - '#Unsafe usage of new static#'

    checkMissingIterableValueType: false

    parallel:
        maximumNumberOfProcesses: 1

```

And output:
```
root@f935f6c02e56:/laravel# ./vendor/bin/phpstan analyse  --debug --verbose
Note: Using configuration file /laravel/phpstan.neon.dist.
PHPStan crashed in the previous run probably because of excessive memory consumption.
It consumed around 57 MB of memory.


To avoid this issue, allow to use more memory with the --memory-limit option.
/laravel/app/Console/Commands/RedisTestJob.php
Killed

```

### Laravel code where the issue was found

```php
Redis::connection(); // or any other function, eg. Redis::get
```
