### ISSUE TITLE
Call to undefined method Application::middleware() while registering Lumen middleware

### ISSUE THREAD

**Issue by bandicsongor** [nunomaduro/larastan#1167]
- Larastan Version: 1.0.3
- `--level` used: 8

### Description
I'm testing a package where I have a ServiceProvider which registers a middleware:
```php
// File: package/src/ServiceProvider.php
class ServiceProvider extends Illuminate\Support\ServiceProvider
{
    public function boot(): void
    {
        $this->app->middleware([
            \Package\Middleware\FooBarMiddleware::class,
        ]);
    }
}
```
And when I run the phpstan generates the next error:
```
Error thrown in /src/ServiceProvider.php on line 13 while loading bootstrap file package/vendor/nunomaduro/larastan/bootstrap.php: Call to undefined method Illuminate\Foundation\Application::middleware()
````

**Comment by szepeviktor** [comment]
Szia Csongor!
Thank you for your report.
Do you have Testbench installed?

**Comment by bandicsongor** [comment]
Szia,
Yes, I have: v6.24.0

**Comment by szepeviktor** [comment]
> File: package/src/ServiceProvider.php

Do you have a monorepo with several packages?

**Comment by bandicsongor** [comment]
Sorry, but I don't know what is that :) but I've made a sample project.

Unzip -> composer install -> vendor/bin/phpstan

[larastan-sample.zip](https://github.com/nunomaduro/larastan/files/8240561/larastan-sample.zip)

**Comment by szepeviktor** [comment]
Is your goal to register a **Lumen** middleware?
https://lumen.laravel.com/docs/8.x/middleware#registering-middleware 👀

**Comment by bandicsongor** [comment]
Yes

**Comment by szepeviktor** [comment]
Have you tried to do it in a local `bootstrap/app.php` file as it is in the above docs?

**Comment by bandicsongor** [comment]
This is the main spec, I have to implement a package which registers some middlewares in all the APIs (which includes this package)

I've tried to overwrite the phpstan bootstrap file in my phpstan.neon.dist file but it's not working, still using the bootstrap file from the included extension.neon:

```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:
    bootstrapFiles:
        - phpstan_bootstrap.php
    level: 8
    paths:
        - src
    ignoreErrors:
        -
            message: '#Call to an undefined method object#'
            path: src/Routing.php

    checkMissingIterableValueType: false
```
