### ISSUE TITLE
Testbench cache directory missing on GitHub Actions

### ISSUE THREAD

**Issue by vlasscontreras** [nunomaduro/larastan#1202]
- Larastan Version: 2.1.3
- `--level` used: 9

### Description

Executing `./vendor/bin/phpstan --no-progress` locally works fine, but on GitHub actions results in the following error:

```
Note: Using configuration file /home/runner/work/.../phpstan.neon.
Exception thrown in /home/runner/work/.../vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php on line 1[7](https://github.com/.../runs/...?check_suite_focus=true#step:5:7)8 while loading bootstrap file /home/runner/work/.../vendor/nunomaduro/larastan/bootstrap.php: The /home/runner/work/.../vendor/orchestra/testbench-core/laravel/bootstrap/cache directory must be present and writable.
```

The testbench (`orchestra/testbench`) is installed because this is a Laravel package and not an application (in which cases works just fine). It looks like it's related to permissions on testbench-created directories used by Larastan. Is there an additional step required to make it work on GitHub actions?

### GitHub Action job

The following has no cache as an attempt to fix it because I realized that when using `actions/cache` the permission issue chance might be more likely to happen.

```yaml
name: SCA

on: [pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.0", "8.1"]

    name: PHPStan (PHP ${{ matrix.php }})

    steps:
    - name: Checkout 🛎
      uses: actions/checkout@v2

    - name: Install Dependencies 👨🏻‍💻
      uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.php }}
        ssh_key: ${{ secrets.SSH_KEY_PRIV }}
        ssh_key_pub: ${{ secrets.SSH_KEY_PUB }}

    - name: Run PHPStan 🧐
      run: ./vendor/bin/phpstan --no-progress
```

Thank you for your help! 😁
