### ISSUE TITLE
Access to an undefined property Illuminate\Database\Eloquent\Model::$id.

### ISSUE THREAD

**Issue by misusonu18** [nunomaduro/larastan#1265]
- Larastan Version: 2.1.8
- `8-level` used:

### Getting the Issue of Access to undefined property Model::$id
But in local I have created the stub file and added the property id on it but still getting the issue.

### Error PhpStan
![image](https://user-images.githubusercontent.com/52093984/172096066-f01440c8-eb33-4d22-9ede-e40c6628f3cc.png)

### Model.stub File
![image](https://user-images.githubusercontent.com/52093984/172096115-f808431b-b63e-4f4a-9464-6468cedb2552.png)

**Comment by hmingv** [comment]
Modify the type declaration of the model object to be your own model object instead of the Model base class.

Also, why are you modifying any files inside vendor?

**Comment by hirenkeraliya** [comment]
We are not changing the actual vendor file but using the stub feature of the PHPSTAN. One more thing this model is anything either the Admin, User, StoreManager anything that's why we need to declare its base model.

**Comment by misusonu18** [comment]
in larastan version 2.1.6 was working perfectly, In larastan update to version 2.1.8 we got this kind of issue.

**Comment by szepeviktor** [comment]
Larastan reads model properties from migrations files.
https://github.com/nunomaduro/larastan/blob/58133e5205d6720d0356540d718090802214b5b4/tests/Application/database/migrations/2020_10_04_000000_create_posts_table.php#L19

**Comment by hirenkeraliya** [comment]
> Larastan reads model properties from migrations files.
> 
> https://github.com/nunomaduro/larastan/blob/58133e5205d6720d0356540d718090802214b5b4/tests/Application/database/migrations/2020_10_04_000000_create_posts_table.php#L19

OK. But this will works in the larastan 2.1.6. Why it's not working on the 2.1.8?

**Comment by szepeviktor** [comment]
Could you share your model's code? It could be a generics or closure problem.

**Comment by misusonu18** [comment]
We have followed the steps as per https://phpstan.org/user-guide/stub-files

Stub FIle
```
<?php

namespace Illuminate\Database\Eloquent;

/**
 * @implements \ArrayAccess<string, mixed>
 * @property int $id
 */
abstract class Model implements \JsonSerializable, \ArrayAccess
{
    /**
     * @var array<string, string>
     */
    protected $casts = [];

    /**
     * @var list<string>
     */
    protected $hidden = [];

    /**
     * @var list<string>
     */
    protected $visible = [];

    /**
     * Update the model in the database.
     *
     * @param  array<model-property<static>, mixed>  $attributes
     * @param  array<int|string, mixed>  $options
     * @return bool
     */
    public function update(array $attributes = [], array $options = []);

    /**
     * Begin querying a model with eager loading.
     *
     * @param  string|array<int|string, (\Closure)|string>  $relations
     * @return \Illuminate\Database\Eloquent\Builder<static>
     */
    public static function with($relations);
}

class ModelNotFoundException extends \RuntimeException {}
```

Service Class
```
public function addNew(Model $affectedBy, array $data): void {
	$data['affected_by_id'] = $affectedBy->id;
	$data['affected_by_type'] = $affectedBy::class;
	Admin::create($data);
}
```
phpstan.neon file
---------------------------------------------------
```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:
    parallel:
        maximumNumberOfProcesses: 5
        minimumNumberOfJobsPerProcess: 2

    paths:
        - app

    stubFiles:
        - stubs/Model.stub

    # The level 9 is the highest level
    level: 8

    checkMissingIterableValueType: false

    checkGenericClassInNonGenericObjectType: false

```
