### ISSUE TITLE
Use of a local scope inside another scope definition is not allowed

### ISSUE THREAD

**Issue by pacoorozco** [nunomaduro/larastan#1307]
- Larastan Version: 1.7.13
- `--level` used: 8
- Pull request with failing test: https://github.com/pacoorozco/gamify-laravel/pull/268

### Description
Using a already defined local scope in another scope is raised as error.

```
------ ----------------------------------------------------------------------------- 
  Line   app/Models/Badge.php                                                         
 ------ ----------------------------------------------------------------------------- 
  109    Call to an undefined method Illuminate\Database\Eloquent\Builder::active().  
 ------ ----------------------------------------------------------------------------- 
```

### Laravel code where the issue was found

```php
102: public function scopeActive(Builder $query): Builder
103:    {
104:        return $query->where('active', true);
105:    }
106:
107:    public function scopeWithActuatorsIn(Builder $query, array $actuators): Builder
107:    {
109:        return $query
110:            ->active() 👈🏻 
111:            ->hasAnyFlags('actuators', $actuators);
112:    }
```

**Comment by szepeviktor** [comment]
Thank you for your report!

What does PHPStan say to this?
```php
109:        return $query
110:            ->where('active', true)
111:            ->hasAnyFlags('actuators', $actuators);
```

**Comment by pacoorozco** [comment]
```
------ ---------------------------------------------------------------------------------- 
  Line   app/Models/Badge.php                                                              
 ------ ---------------------------------------------------------------------------------- 
  109    Call to an undefined method Illuminate\Database\Eloquent\Builder::hasAnyFlags().  
 ------ ---------------------------------------------------------------------------------- 
```

The `phpstan.neon` file includes the BenSampo integration:

```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
    - ./vendor/bensampo/laravel-enum/extension.neon

parameters:

    paths:
        - app
        - config
        - database
        - routes

    # The level 9 is the highest level
    level: 8

    excludePaths:
        - ./*/*/FileToBeExcluded.php

    checkMissingIterableValueType: false
    checkGenericClassInNonGenericObjectType: false
```
