### ISSUE TITLE
Larastan is not working with database factories

### ISSUE THREAD

**Issue by danielcosta** [nunomaduro/larastan#144]
- Larastan Version: 0.2.11
- `--level` used: 0

### Description:
The magic side of larastan is not working with database factories and the error below is shown when analysing this kind of file:
```
 ------ -------------------------------------------------- 
  Line   database/factories/MyModel.php  
 ------ -------------------------------------------------- 
  6      Undefined variable: $factory                      
 ------ -------------------------------------------------- 
```

### Laravel code where the issue was found:
```php
use Faker\Generator as Faker;
use App\MyModel;

$factory->define(MyModel::class, function (Faker $faker) {
    return [
        'id' => $faker->randomDigit(),
        'description' => $faker->sentence(6, true),
    ];
});
```

Is there any way to analyse or simply ignore these files temporarily?

**Comment by danielcosta** [comment]
Great! While this analysis is not provided by phpstan itself, it's working with this snippet of configuration:

```yaml
includes:
    - vendor/nunomaduro/larastan/extension.neon

parameters:
    excludes_analyse:
        - %rootDir%/../../../*/factories/*.php
```

And the command to use the custom conf file is:

```
$ ./artisan code:analyse --paths='app,modules' --level=0 --configuration=/path/to/app/phpstan.neon
```

Thank you very much!
