### ISSUE TITLE
Call to an undefined static method Model::count()

### ISSUE THREAD

**Issue by bistory** [nunomaduro/larastan#1442]
- Larastan Version: 2.2
- `--level` used: 1

### Description

Hi,
I just installed Larastan (I already used it on previous projects).
I'm facing a strange issue I never encountered before... On a simple model, when I call the static count method without "where" before, Larastan screams the method doesn't exist, while it exists as my code works...

I guess it's a false positive.

### Laravel code where the issue was found
Category class is extending Illuminate\Database\Eloquent\Model class

```php
$categories = Category::count();
```

**Comment by canvural** [comment]
Hi,

I'm pretty sure this is an issue with your setup somehow. I cannot reproduce it locally.

You need to give more info like, your PHPStan config, any other extensions, maybe docblocks in your model etc.


Or you can provide a failing test case here, or a repository where you can reproduce it.

**Comment by bistory** [comment]
That's strange, this project is new and pretty standard...

Here is my configuration : 

```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:

    paths:
        - app
        - config
        - database
        - routes
#        - tests

    # The level 8 is the highest level
    level: 1

    checkMissingIterableValueType: false
    checkGenericClassInNonGenericObjectType: false

    universalObjectCratesClasses:
        - Illuminate\Database\Eloquent\Builder
        - Laravel\Socialite\Contracts\User
        - App\Models\Ad
        - App\Models\Category
        - App\Models\ConnectedAccount
        - App\Models\User
```

And the model file : 

```
<?php

namespace App\Models;

use Fureev\Trees\NestedSetTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Category extends Model
{
    use HasFactory;
    use HasSlug;
    use NestedSetTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'ebay',
    ];

    /**
     * Return the sluggable configuration object for this model.
     *
     * @return SlugOptions
     */
    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug');
    }

    /**
     * Return ads that are in the category.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany<\App\Models\Ad>
     */
    public function ads()
    {
        return $this->hasMany(Ad::class);
    }

    /**
     * Scope a query to only include popular users.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeLinked($query)
    {
        return $query->where('ebay', '!=', '');
    }
}
```
