### ISSUE TITLE
 Too few arguments passed to function

### ISSUE THREAD

**Issue by phily245** [nunomaduro/larastan#1448]
- Larastan Version: 2.0.0
- `--level` used: 6
- Pull request with failing test: underway

### Description

When using a short arrow function to filter a collection, I get the stack trace below:

```
./vendor/bin/phpstan --configuration=.phpstan/phpstan.neon analyse --error-format=raw --memory-limit=4G tests/.../AlertTest.php -v

 ! [NOTE] The Xdebug PHP extension is active, but "--xdebug" is not used. This may slow down performance and the process
 !        will not halt at breakpoints.                                                                                 

 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%  1 sec

?:?:Internal error: Internal error: Too few arguments to function PHPStan\Analyser\MutatingScope::assignVariable(), 2 passed in /var/www/html/vendor/nunomaduro/larastan/src/ReturnTypes/CollectionFilterDynamicReturnTypeExtension.php on line 90 and at least 3 expected in file /var/www/html/tests/Unit/Elasticsearch/Maps/AlertTest.php

Post the following stack trace to https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md: 
#0 /var/www/html/vendor/nunomaduro/larastan/src/ReturnTypes/CollectionFilterDynamicReturnTypeExtension.php(90): PHPStan\Analyser\MutatingScope->assignVariable('baz', Object(PHPStan\Type\StringType))
#1 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3488): NunoMaduro\Larastan\ReturnTypes\CollectionFilterDynamicReturnTypeExtension->getTypeFromMethodCall(Object(PHPStan\Reflection\ResolvedMethodReflection), Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScope))
#2 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1402): PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\Generic\GenericObjectType), 'filter', Object(PhpParser\Node\Expr\MethodCall))
#3 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1408): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#4 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(557): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\MethodCall))
#5 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1437): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))
#6 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(554): PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr(Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScope))
#7 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(357): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#8 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1101): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Expr\Closure), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#9 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(557): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\Closure))
#10 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Rules/FunctionCallParametersCheck.php(114): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\Closure))
#11 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Functions/CallToFunctionParametersRule.php(46): PHPStan\Rules\FunctionCallParametersCheck->check(Object(PHPStan\Reflection\FunctionVariantWithPhpDocs), Object(PHPStan\Analyser\MutatingScope), false, Object(PhpParser\Node\Expr\FuncCall), Array)
#12 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(106): PHPStan\Rules\Functions\CallToFunctionParametersRule->processNode(Object(PhpParser\Node\Expr\FuncCall), Object(PHPStan\Analyser\MutatingScope))
#13 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2460): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Expr\FuncCall), Object(PHPStan\Analyser\MutatingScope))
#14 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1462): PHPStan\Analyser\NodeScopeResolver->callNodeCallbackWithExpression(Object(Closure), Object(PhpParser\Node\Expr\FuncCall), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Analyser\ExpressionContext))
#15 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1651): PHPStan\Analyser\NodeScopeResolver->processExprNode(Object(PhpParser\Node\Expr\FuncCall), Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\ExpressionContext))
#16 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(555): PHPStan\Analyser\NodeScopeResolver->processExprNode(Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\ExpressionContext))
#17 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(327): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#18 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(175): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#19 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(147): PHPStan\Analyser\FileAnalyser->analyseFile('/var/www/html/t...', Array, Object(PHPStan\Rules\LazyRegistry), Object(PHPStan\Collectors\Registry), NULL)
#20 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): PHPStan\Command\WorkerCommand->PHPStan\Command\{closure}(Array)
#21 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(110): _PHPStan_582a9cb8b\Evenement\EventEmitter->emit('data', Array)
#22 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): _PHPStan_582a9cb8b\Clue\React\NDJson\Decoder->handleData(Array)
#23 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(62): _PHPStan_582a9cb8b\Evenement\EventEmitter->emit('data', Array)
#24 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): _PHPStan_582a9cb8b\React\Stream\Util::_PHPStan_582a9cb8b\React\Stream\{closure}('{"action":"anal...')
#25 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(154): _PHPStan_582a9cb8b\Evenement\EventEmitter->emit('data', Array)
#26 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201): _PHPStan_582a9cb8b\React\Stream\DuplexResourceStream->handleData(Resource id #7438)
#27 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173): _PHPStan_582a9cb8b\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
#28 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(107): _PHPStan_582a9cb8b\React\EventLoop\StreamSelectLoop->run()
#29 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\WorkerCommand->execute(Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Output\ConsoleOutput))
#30 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(868): _PHPStan_582a9cb8b\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Output\ConsoleOutput))
#31 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(259): _PHPStan_582a9cb8b\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\WorkerCommand), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Output\ConsoleOutput))
#32 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_582a9cb8b\Symfony\Component\Console\Application->doRun(Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Output\ConsoleOutput))
#33 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124): _PHPStan_582a9cb8b\Symfony\Component\Console\Application->run()
#34 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_582a9cb8b\{closure}()
#35 /var/www/html/vendor/phpstan/phpstan/phpstan(8): require('phar:///var/www...')
#36 /var/www/html/vendor/bin/phpstan(120): include('/var/www/html/v...')
#37 {main}
?:?:Child process error (exit code 1): 
Used memory: 82.5 MB
```

phpstan.neon:

```
includes:
    - ../vendor/nunomaduro/larastan/extension.neon

parameters:
    stubFiles:
        - stubs/Model.stub

    paths:
        - ../

    level: 6

    reportUnmatchedIgnoredErrors: false

    ignoreErrors:
        # Laravel ignore
        - '#Call to an undefined method Illuminate\\Support\\HigherOrder#'

        # App Ignores
        -
            message: '#Static call to instance method [a-zA-Z0-9\\_].#'
            path: ../app/Providers/ResponseServiceProvider.php
        -
            message: '#Undefined variable: \$this#'
            path: ../routes/console.php
        -
            message: '#Call to an undefined method Illuminate\\Database\\Eloquent\\Collection<int, Illuminate\\Database\\Eloquent\\Model>|Illuminate\\Database\\Eloquent\\Model::setUkFastConsumer\(\).#'
            path: ../routes/console.php
        -
            message: '#Cannot call method toIso8601String\(\) on string.#'
            path: ../app
        -
            message: '#Call to an undefined method UKFast\\SDK\\Account\\Client.*?#'
            path: ../app
        -
            message: '#Call to an undefined method Illuminate\\Contracts\\Auth\\Authenticatable.*?#'
            path: ../app
        -
            message: '#Call to an undefined method Illuminate\\Database\\Eloquent\\Builder::withTrashed\(\).#'
            path: ../app/Models

        # Test ignores
        -
            message: '#Undefined variable: \$this#'
            path: ../tests
        -
            message: '#Call to an undefined method Mockery\\ExpectationInterface|Mockery\\HigherOrderMessage::#'
            path: ../tests
        -
            message: '#Call to an undefined method Pest\\Expectation|Pest\\Support\\Extendable::#'
            path: ../tests
        -
            message: '#Access to an undefined property Pest\\Expectation::\$data.#'
            path: ../tests
        -
            message: '#Parameter .*? expects .*?, Mockery\\LegacyMockInterface.*? given#'
            path: ../tests
        -
            message: '#Access to an undefined property Illuminate\\Database\\Eloquent\\Collection<int, Illuminate\\Database\\Eloquent\\Model>|Illuminate\\Database\\Eloquent\\Model::\$id.#'
            path: ../tests
        -
            message: '#Call to an undefined method Illuminate\\Database\\Eloquent\\Collection<int, Illuminate\\Database\\Eloquent\\Model>|Illuminate\\Database\\Eloquent\\Model::setUkFastConsumer\(\).#'
            path: ../tests
        -
            message: '#Access to an undefined property Pest\\Expectation::.+#'
            path: ../tests

    excludePaths:
        - ../vendor
        - ../storage/framework/views

    checkMissingIterableValueType: false

```

LoC it is mentioning: https://github.com/nunomaduro/larastan/blob/master/src/ReturnTypes/CollectionFilterDynamicReturnTypeExtension.php#L91

### Laravel code where the issue was found

```php
(new Collection(['foo' => 'bar']))->filter(fn (string $baz, string $qux) => $qux);
```
