### ISSUE TITLE
Views not analyzed with config `viewDirectories` 

### ISSUE THREAD

**Issue by nwehrhan** [nunomaduro/larastan#1900]
- Larastan Version: 2.3.5
- `--level` used: 8
- Pull request with failing test:

### Description
With this config phpstan doesn't analyze the views files 
`/vendor/bin/phpstan analyze  --level=8 --memory-limit=2G --debug`
```
includes:
    - phpstan-baseline.neon
    - vendor/jangregor/phpstan-prophecy/extension.neon
    - vendor/larastan/larastan/extension.neon
    - vendor/phpstan/phpstan-mockery/extension.neon
parameters:
    level: 8
    reportUnmatchedIgnoredErrors: false
    paths:
        - resources/themes
    viewDirectories:
        - resources/themes
```
Output
```
82/82 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 [OK] No error
 ```

If I remove larastan and the viewDirectories config phpstan finds the view files
`/vendor/bin/phpstan analyze  --level=8 --memory-limit=2G --debug`
```
includes:
    - phpstan-baseline.neon
    - vendor/jangregor/phpstan-prophecy/extension.neon
    - vendor/larastan/larastan/extension.neon
    - vendor/phpstan/phpstan-mockery/extension.neon
parameters:
    level: 8
    reportUnmatchedIgnoredErrors: false
    paths:
        - resources/themes
    viewDirectories:
        - resources/themes
```
Output:
` ! [NOTE] No files found to analyse.`

Am I doing something wrong with the config? Been banging head on this.
