### ISSUE TITLE
phpstan.neon paths not working

### ISSUE THREAD

**Issue by loic-lopez** [nunomaduro/larastan#202]
- Larastan Version: 0.3.8
- `--level` used: max

### Description:
Modifying paths in phpstan.neon changes nothing, it always use my app directory and only.

### Laravel code where the issue was found:
Bellow my phpstan.neon

```yaml
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
parameters:
    excludes_analyse:
        - /*/Definitions/*
    level: max
    ignoreErrors:
        - '#Laravel\\Passport\\ClientRepository::createPasswordGrantClient()#'
        - '#Illuminate\\Database\\Query\\Builder::dynamicWhere()#'
    paths:
        - %rootDir%/../../../app
        - %rootDir%/../../../routes
        - %rootDir%/../../../tests
        - %rootDir%/../../../database

```
