### ISSUE TITLE
Incorrectly reporting: Called 'env' outside of the config directory which returns null when the config is cached, use 'config'.

### ISSUE THREAD

**Issue by SlyDave** [nunomaduro/larastan#2043]
- Larastan Version: 2.9.8
- Laravel Version: 11.23.4

### Description

phpstan is reporting `phpstan: Called 'env' outside of the config directory which returns null when the config is cached, use 'config'.`

When the call is inside a file in the config directory

`config_path();` = `"C:\www\<project>\config"`
file = `C:\www\<project>\config\filesystems.php`

![image](https://github.com/user-attachments/assets/4fc44464-405a-4672-a28f-77333b94f123)

![image](https://github.com/user-attachments/assets/9714c2bf-0b9f-4de2-8f81-97d9692919e9)

**Comment by szepeviktor** [comment]
Could be a Windows-related issue.
Try dumping values here:
https://github.com/larastan/larastan/blob/e1b64a0f3120cf40fca9703a718e29b0cef89f9f/src/Rules/NoEnvCallsOutsideOfConfigRule.php#L61

**Comment by SlyDave** [comment]
Seems to be something to do with how PHPStorm is running phpstan :(

![image](https://github.com/user-attachments/assets/29b7884a-fd8d-4caf-b70e-6e4034c8df6a)
![image](https://github.com/user-attachments/assets/d0d6e574-3a8f-414d-8ae9-c0a235d21b04)

**Comment by canvural** [comment]
PHPStorm can indeed act weird. Maybe it doesn't pickup the correct PHPStan config. Please re-open the issue only if it also happens when running PHPStan from cli.

**Comment by daniser** [comment]
@canvural it happened to me during execution from CLI: https://github.com/ttbooking/support-chat/runs/34828663022
But, my project is Laravel package. Can I somehow let Larastan know what my config directory is, or maybe Larastan need config dir auto-detection algorithm for packages?

**Comment by calebdw** [comment]
@daniser, don't scan your package config directory--- just the source code

**Comment by ElvisIsKing666** [comment]
In case it isn't obvious to others who find this issue, the problem is that PhpStorm runs the check in a private temp directory and the larastan code is checking the absolute file path of the file against the absolute file path of the config directory and it fails.

You can make it work by creating a separate phpstan-phpstorm.neon file:
```
# phpstan-phpstorm.neon
# This configuration is specifically for PHPStorm's real-time inspection.
# It inherits all rules from the main config but disables the 'env()' check
# for config files, which gives false positives due to the IDE using temp files.

includes:
    - ./phpstan.neon

parameters:
    ignoreErrors:
        -
            message: "#^Called 'env' outside of the config directory which returns null when the config is cached, use 'config'.$#"
            path: *config/*.php
```
