### ISSUE TITLE
Testbench being taken into account for `noEnvCallsOutsideOfConfigRule`

### ISSUE THREAD

**Issue by ollosh** [nunomaduro/larastan#2139]
# Feature Request

I have a package for which we've created config files inside the `config` directory. When I run phpstan now, it complains that
```
Called 'env' outside of the config directory which returns null when the config is cached,
 use 'config'.
  🪪  larastan.noEnvCallsOutsideOfConfig
```

Is there a way you could take testbench into account when running this rule because `config_path()` method in the package returns `/app/vendor/orchestra/testbench-core/laravel/config` this folder?

**Additional context**

`package structure`
```
- app
    - package code
    - PackageProvider
- config
    - package config file 1
    - package config file 2
- vendor
    - orchestra
        - testbench-core
            - laravel
                - config <= this is where laravel's `config_path` helper points to
```

`phpstan.neon`
```
includes:
    - phpstan-baseline.neon

parameters:
    level: 6
    paths:
        - app
        - config
        - tests
    checkModelProperties: true
    ignoreErrors:
        - identifier: missingType.iterableValue
        - identifier: larastan.noEnvCallsOutsideOfConfig
```
