### ISSUE TITLE
Collection methods map, mapWithKeys reports error argument.unresolvableType

### ISSUE THREAD

**Issue by mahdiabderraouf** [nunomaduro/larastan#2278]
Larastan Version: v3.4.0
Laravel Version: 12.12.0

### Description
Larastan reports an argument.unresolvableType error for a callback passed to Collection::map() even though the collection is properly annotated with a generic PHPDoc type.

This seems to be a false positive. The collection is annotated as Collection<int, \App\Models\Item> and the closure parameter is correctly type-hinted as Item. Despite this, Larastan still throws the error.

Attempts to work around this using `@var` annotations or casting with collect() do not resolve the issue.

### The error:
```
Parameter #1 $callback of method Illuminate\Support\Collection<int,App\Models\Item>::map() contains unresolvable type.  
 🪪  argument.unresolvableType
```

### Laravel code where the issue was found
```php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use Illuminate\Support\Collection;

class ItemController extends Controller
{
    /**
     * @param Collection<int, Item> $items
     */
    public function calculateDiscounts(Collection $items): array
    {
        $result = $items->map(function (Item $item) {
            return [
                'price' => $item->price,
                'discounted' => $item->price * 0.9,
            ];
        });

        return $result->toArray();
    }
}
```

### Expected Behavior
Larastan should correctly resolve the type of $item in the closure from the collection's generic annotation and not report the callback type as unresolvable.

**Comment by szepeviktor** [comment]
Try adding `: array` to the closure, and remove parts of the closure to narrow down the error.

**Comment by calebdw** [comment]
Can you show your full item model?

**Comment by mahdiabderraouf** [comment]
@szepeviktor Still getting the same error by narrowing down the array, i dont have the error if i return string for test purpose

```php
// No error
$items->map(function (Item $item): string {
        return $item->title;
});
```

**Comment by mahdiabderraouf** [comment]
@calebdw Yes ofcrs

```php

use Awobaz\Compoships\Compoships;
use App\Traits\CompanyIdScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Auth;

class Item extends Model
{
    use Compoships;
    use HasFactory;
    use CompanyIdScope;

    public $timestamps = false;

    protected $primaryKey = 'ITEMID';

    protected $table = 'ITEM';
}
```

**Comment by mahdiabderraouf** [comment]
I found the solution, i have to explicitly cast the array properties to float:

```php
$items->map(function (Item $item): array {
            return [
                'price' => (float) $item->price,
                'discounted' => (float) $item->price * 0.9,
            ];
        });
```

**Comment by calebdw** [comment]
You shouldn't have to do that, it's likely not able to determine what type the price property is

**Comment by mahdiabderraouf** [comment]
How can i make larastan detects the type of model property ? Or how can i ignore this rule ?

**Comment by calebdw** [comment]
What is the output of:

```php
\PHPStan\dumpType($item->price);
```

**Comment by mahdiabderraouf** [comment]
@calebdw 

```
Dumped type: *ERROR*  
```

**Comment by szepeviktor** [comment]
You may have problems with SQL migrations. Properties come from there.

**Comment by calebdw** [comment]
That would be why. Is this a database property or a computed accessor? What database are you using? What does your Larastan config look like? Are you squashing your migrations?

**Comment by mahdiabderraouf** [comment]
Im not squashing migrations, but im working with an old database where all fields are in uppercase, maybe the probleme come from here ?

**Comment by calebdw** [comment]
That might be it, what does this show?

```php
\PHPStan\dumpType($item->PRICE);
```

**Comment by mahdiabderraouf** [comment]
@calebdw my field name is PUHT, in french it means "unit price without vat", in the example for simplicity i used `price`, here is the ouput of `\PHPStan\dumpType($item->PUHT);`:
```
76     Dumped type: *ERROR*
```

And here is my migration file, just a note my migration are generated using the package `kitloong/laravel-migrations-generator` :

```
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('ITEM', function (Blueprint $table) {
            $table->collation = 'utf8_general_ci';
            $table->charset = 'utf8';

            $table->increments('ITEMID');
            $table->integer('COMPANYID')->index('companyid');
            $table->integer('USERID');
            $table->smallInteger('ITYPE')->default(1)->comment('Type de ligne 1:article;2:texte;3:sous total');
            $table->integer('POSITION')->nullable();
            $table->string('AREF', 25)->nullable();
            $table->string('PICTURE', 200)->nullable();
            $table->text('ANAME');
            $table->double('QUANTITY');
            $table->string('CODEUNIT', 10)->nullable()->comment('Code unit� de la ligne');
            $table->double('PUHT');
            $table->double('CPUHT')->nullable()->default(0)->comment('PUHT en devise');
            $table->double('PUTTC')->nullable()->default(0);
            $table->double('CPUTTC')->nullable()->default(0)->comment('PUTTC en devise');
            $table->double('IREBATE')->nullable()->default(0);
            $table->double('CIREBATE')->nullable()->default(0)->comment('Remise � la ligne en devise');
            $table->double('IREBATETTC')->nullable()->default(0);
            $table->double('CIREBATETTC')->nullable()->default(0)->comment('Remise TTC � la ligne en devise');
            $table->string('ITYPEREBATE', 10)->nullable();
            $table->double('IPERCENT')->nullable();
            $table->integer('TVAID')->default(0);
            $table->double('PUBUYHT')->nullable()->default(0)->comment('Prix d achat');
            $table->double('CPUBUYHT')->nullable()->default(0)->comment('Coefficient de la marge');
            $table->double('COEFFICIENT')->nullable()->default(0)->comment('Coefficient de la marge');
            $table->double('MARGIN_PERCENT')->nullable()->default(0)->comment('Pourcentage de la marge');
            $table->double('REAL_MARGIN_PERCENT')->nullable()->default(0)->comment('Le vrai taux de marge');
            $table->double('MARGIN')->nullable()->default(0)->comment('Marge en montant');
            $table->double('CMARGIN')->nullable()->default(0)->comment('MARGIN en devise');
            $table->double('TVA')->default(0);
            $table->double('TOTALTVA')->default(0);
            $table->double('CTOTALTVA')->default(0);
            $table->double('TOTALHT');
            $table->double('CTOTALHT')->nullable()->default(0)->comment('Total de la ligne en devise');
            $table->double('TOTALTTC')->nullable()->default(0);
            $table->double('CTOTALTTC')->nullable()->default(0)->comment('Total TTC de la ligne en devise');
            $table->double('TOTALBUYHT')->nullable()->default(0);
            $table->double('CTOTALBUYHT')->nullable()->default(0);
            $table->integer('INVOICEID')->nullable()->index('invoiceid');
            $table->integer('QUOTEID')->nullable()->index('quoteid');
            $table->integer('CORDERID')->nullable()->index('corderid');
            $table->integer('DELIVERYID')->nullable()->index('deliveryid');
            $table->integer('CREDITID')->nullable()->index('creditid');
            $table->integer('ADVANCEID')->nullable()->index('advanceid');
            $table->integer('PORDERID')->nullable()->index('porderid');
            $table->integer('RECEIPTID')->nullable()->index('receiptid');
            $table->integer('ARTICLEID')->nullable();
            $table->integer('GROUPID')->nullable()->comment('Id du group de la ligne');
            $table->string('CLASSCODE', 250)->nullable();
            $table->double('CONVERSION')->default(1)->comment('Taux de conversion');
            $table->integer('REFITEMID')->nullable()->index('refitemid')->comment('id de l item pere');
            $table->double('WEIGHT')->nullable()->comment('poids des items (BL)');
            $table->float('PROGRESSION')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('ITEM');
    }
};

```

**Comment by calebdw** [comment]
Interesting, where is that migration being stored and how is Larastan configured?

**Comment by mahdiabderraouf** [comment]
Migrations are stored in `database/migrations` and here is my larastan config:

```
includes:
    - vendor/larastan/larastan/extension.neon

parameters:
    paths:
        - app

    level: 5

    ignoreErrors:
        - '#Access to an undefined property [App\\Models\\[A-Za-z0-9_-]+|\$this\(App\\Models\\[A-Za-z0-9_-]+\)|Illuminate\\Database\\Eloquent\\Model]::#'
        - # Error in Files where STS\HubSpot\Crm\Contact::where is called
            message: '#Call to an undefined static method STS\\HubSpot\\Crm\\Contact::where#'
            paths:
                - app/Listeners/SendSubscriptionToHubspot.php
        - # Error in Files where phpstan is lost with Eloquent Builder
            message: '#Call to an undefined method Illuminate\\Database\\Eloquent\\Builder::limitedView#'
            paths:
                - app/Http/Controllers/Reports/OverduePaymentController.php
                - app/Http/Controllers/Reports/OverdueSettlementController.php
                - app/Repositories/TurnoverRepository.php
    excludePaths:
        - ./app/SymfonyTransports/*.php
        - *.blade.php

    disableMigrationScan: true
    disableSchemaScan: true
    checkPhpDocMissingReturn: false
    treatPhpDocTypesAsCertain: false
```

Well now i see that migration scan is disabled. This maybe the problem.
