### ISSUE TITLE
PHPStan cannot resolve Request methods

### ISSUE THREAD

**Issue by Grafikart** [nunomaduro/larastan#2279]
- Larastan Version: 3.4.0
- Laravel Version: 12.11.1
- Laravel IDE Helper : 3.5.5

### Description

I'm working on a new laravel project and it doesn't understand any method coming from the Request object. Is there a way to have additional detail to help debug this issue ?

```bash
 ------ ------------------------------------------------------------------------------------------- 
  Line   Domains/Estimates/Requests/EstimateFormRequest.php                                         
 ------ ------------------------------------------------------------------------------------------- 
  17     Call to an undefined method App\Domains\Estimates\Requests\EstimateFormRequest::method().  
         🪪  method.notFound                                                                        
  18     Call to an undefined method App\Domains\Estimates\Requests\EstimateFormRequest::user().    
         🪪  method.notFound                                                                        
  21     Call to an undefined method App\Domains\Estimates\Requests\EstimateFormRequest::route().   
         🪪  method.notFound                                                                        
  26     Call to an undefined method App\Domains\Estimates\Requests\EstimateFormRequest::user().    
         🪪  method.notFound                                                                        
  31     Call to an undefined method App\Domains\Estimates\Requests\EstimateFormRequest::merge().   
         🪪  method.notFound                                                                        
  47     Call to an undefined method App\Domains\Estimates\Requests\EstimateFormRequest::user().    
         🪪  method.notFound                                                                        
  66     Call to an undefined method App\Domains\Estimates\Requests\EstimateFormRequest::route().   
         🪪  method.notFound                                                                        
 ------ ------------------------------------------------------------------------------------------- 
```

It also happens in FormRequest in the default directory. 

### Laravel code where the issue was found

```php
<?php

namespace App\Domains\Estimates\Requests;

use App\Models\Estimate;
use Illuminate\Database\Query\Builder;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class EstimateFormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        if ($this->method() === 'POST') {
            return $this->user()->can('create', Estimate::class);
        }
    }

   //...
}
```

My phpstan.neon file

```yaml
includes:
    - vendor/larastan/larastan/extension.neon
    - vendor/nesbot/carbon/extension.neon

parameters:

    paths:
        - app/

    # Level 10 is the highest level
    level: 5
    scanFiles:
        - _ide_helper.php
        - _ide_helper_models.php
        - .phpstorm.meta.php

#    ignoreErrors:
#        - '#PHPDoc tag @var#'
#
#    excludePaths:
#        - ./*/*/FileToBeExcluded.php

```
