### ISSUE TITLE
Configuration Ignored

### ISSUE THREAD

**Issue by hskrasek** [nunomaduro/larastan#235]
- Larastan Version: 0.3.15
- `--level` used: N/A

### Description:
Currently testing setting up Larastan in our codebase at work, and something I noticed is that it seems like Larastan is ignoring the custom configuration file I created. It's in the base directory of the application, and looks like the following:

```yaml
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
    - ./vendor/phpstan/phpstan-doctrine/extension.neon
parameters:
    level: 0
```

When I run Larastan with no CLI options passed it still defaults to level 5 though, even if I pass the absolute path via `--configuration=`. Is this intended behavior?
