### ISSUE TITLE
[False positive] Property does not accept Illuminate\Support\Facades\Gate

### ISSUE THREAD

**Issue by spaceemotion** [nunomaduro/larastan#251]
- Larastan Version: 0.3.15
- `--level` used:5

### Description
```
Property App\xxxxx::$gate (Illuminate\Contracts\Auth\Access\Gate) 
does not accept Illuminate\Support\Facades\Gate.
```

According to the `@property`-Hints this method returns an instance of `\Illuminate\Contracts\Auth\Access\Gate` which PHPStan/Larastan seems to ignore:

https://github.com/laravel/framework/blob/c821cbf6f20fca4c50aa9d8fb08f71425afc07b8/src/Illuminate/Support/Facades/Gate.php#L19

### Laravel code where the issue was found

```php
class xxxxx
{
    /**
     * @var \Illuminate\Contracts\Auth\Access\Gate
     */
    private $gate;


    public function __construct(Request $request)
    {
        $this->gate = Gate::forUser($request->user());
    }
}
```

**Comment by danilopolani** [comment]
Idk if I'm doing something wrong here, but I have a similar behaviour and can't solve it. Below my code (using it with Larastan v0.6.8):

```php
use Illuminate\Http\Client\PendingRequest;
use Illuminate\Support\Facades\Http;

abstract class Client
{
  protected PendingRequest $http;

  /**
   * Class constructor.
   *
   * @param array $config - Configuration to setup the HTTP client
   */
  public function __construct(array $config)
  {
    $this->http = Http::baseUrl($config['base_uri']);
  }
}
```

Error returned:

> Property App\Http\Clients\Client::$http (Illuminate\Http\Client\PendingRequest) does not accept Illuminate\Support\Facades\Http.


My `.neon` conf:

```
includes:
  - ./vendor/nunomaduro/larastan/extension.neon

parameters:
  ignoreErrors:
    - '#Call to an undefined method App\\Providers\\MacroServiceProvider::(.*)#'
  paths:
    - app
  level: 6
  checkMissingIterableValueType: false
  reportUnmatchedIgnoredErrors: false
```

@nunomaduro @canvural any idea?
