### ISSUE TITLE
PHPStan\Type\TypeTraverser::mapInternal() with Spatie\QueryBuilder\QueryBuilder

### ISSUE THREAD

**Issue by JonathanGuo** [nunomaduro/larastan#468]
- Larastan Version:  0.5.2
- `--level` used: 5

### Description
It seems like the phpstan cannot analyse `Spatie\QueryBuilder\QueryBuilder` for some unknown reason.

Dependencies:
```json
    "nunomaduro/larastan": "^0.5.2",
    "spatie/laravel-query-builder": "^2.5",
```

`phpstan.neon` configuration

```yaml
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
parameters:
    paths:
        - app
    level: 5
    inferPrivatePropertyTypeFromConstructor: true
    checkMissingIterableValueType: false
```

The internal error output by `vendor/bin/phpstan analyse --debug`:

```
Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to PHPStan\Type\TypeTraverser::mapInternal() must implement interface PHPStan\Type\Type, null given, called in phar:///app/vendor/phpstan/phpstan/phpstan/src/Type/Generic/GenericObjectType.php on line 179

  at phar:///app/vendor/phpstan/phpstan/phpstan/src/Type/TypeTraverser.php:45
    41|     {
    42|         $this->cb = $cb;
    43|     }
    44|     /** @internal */
  > 45|     public function mapInternal(\PHPStan\Type\Type $type) : \PHPStan\Type\Type
    46|     {
    47|         return ($this->cb)($type, [$this, 'traverseInternal']);
    48|     }
    49|     /** @internal */

  Exception trace:

  1   PHPStan\Type\TypeTraverser::mapInternal()
      phar:///app/vendor/phpstan/phpstan/phpstan/src/Type/Generic/GenericObjectType.php:179

  2   PHPStan\Type\Generic\GenericObjectType::traverse()
      phar:///app/vendor/phpstan/phpstan/phpstan/src/Type/TypeTraverser.php:52

  Please use the argument -v to see more details.
```

### Laravel code where the issue was found

Below is a simple code snippet to reproduce the issue

```php
QueryBuilder::for(User::class)
            ->allowedFilters(['name'])
            ->orderBy('name')
            ->get();

```
