### ISSUE TITLE
[0.5.8] Class self was not found while trying to analyse it - autoloading is probably not configured properly.

### ISSUE THREAD

**Issue by johanvanhelden** [nunomaduro/larastan#572]
- Larastan Version: 0.5.8
- `--level` used: 8

### Description
In a model that calls `self::`, Larastan/phpstan crashes:
```
  Line   xxx/Translation.php                                                            
 ------ -------------------------------------------------------------------------------------------------------- 
         Class self was not found while trying to analyse it - autoloading is probably not configured properly.  
         💡 Learn more at https://phpstan.org/user-guide/autoloading  
```

This used to work fine in the version we used before we updated, version v0.5.0.

### Laravel code where the issue was found

```php
    public static function getGroupsByNamespace()
    {
        $groupsByNamespace = self
            ::select('group', 'namespace')
            ->orderBy('namespace')
            ->orderBy('group')
            ->distinct()
            ->get()
            ->groupBy('namespace');

        return $groupsByNamespace;
    }
```

It also happens with a method that uses a scope, like so:

```php
    public function scopeForContext(Builder $query, string $locale, string $namespace, string $group)
    {
        $query->where('locale', $locale)
            ->where('namespace', $namespace)
            ->where('group', $group);
    }

    public static function getGroupTranslations($locale, $group, $namespace)
    {
        return self::forContext($locale, $namespace, $group)
            ->orderBy('name', 'asc')
            ->get();
    }
```

**Comment by canvural** [comment]
Hi, this is not enough to find what is going wrong. 

I'm analyzing code that use `self::` without a problem. Also Larastan has tests that use `self`. No issue there also.

Can you give more info if possible? Any other PHPStan extension, PHPStan version etc.

**Comment by johanvanhelden** [comment]
Hm, sure. 

I have no other extensions. 
The PHPStan version is: 0.12.23
This is what my config looks like:

```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:
    level: 8

    paths:
        - app
        - config
        - tests
        - database
        - modules
        - routes

    ignoreErrors:
        # Test method are the exception for return types
        - '#Method Tests\\(.*)::(.*) has no return typehint specified.#'

        # Unexplainable false positives
        - '#Undefined variable: \$factory#'

    checkMissingIterableValueType: false
    checkUnionTypes: false

    universalObjectCratesClasses:
        - Illuminate\Database\Eloquent\Model

    autoload_directories:
        - database/migrations
```

Maybe good to know, it's inside a model that lives in a module folder:
```
./modules/ModuleName/Models/Translation.php
```
Where normal models live in:
```
./app/Models/xxx.php
```

Therefor the composer.json has been modified like this:
```
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "modules/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
```

**Comment by johanvanhelden** [comment]
Hm, sure. 

I have no other extensions. 
The PHPStan version is: 0.12.23
This is what my config looks like:

```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:
    level: 8

    paths:
        - app
        - config
        - tests
        - database
        - modules
        - routes

    ignoreErrors:
        # Test method are the exception for return types
        - '#Method Tests\\(.*)::(.*) has no return typehint specified.#'

        # Unexplainable false positives
        - '#Undefined variable: \$factory#'

    checkMissingIterableValueType: false
    checkUnionTypes: false

    universalObjectCratesClasses:
        - Illuminate\Database\Eloquent\Model

    autoload_directories:
        - database/migrations
```

Maybe good to know, it's inside a model that lives in a module folder:
```
./modules/ModuleName/Models/Translation.php
```
Where normal models live in:
```
./app/Models/xxx.php
```

The namespace of the model is:

```php
<?php

namespace Modules\ModuleName\Models;
```

Therefor the composer.json has been modified like this:
```json
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "modules/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
```
