### ISSUE TITLE
Undefined index: psr-4

### ISSUE THREAD

**Issue by Flynsarmy** [nunomaduro/larastan#659]
- Larastan Version: ^0.6.0@dev
- `--level` used: 5

### Description
When running `php -d memory_limit=-1 ./vendor/bin/phpstan analyse` I get the error
> ErrorException thrown in /path/to/vendor/nunomaduro/larastan/src/ApplicationResolver.php on line 33 while loading bootstrap file /path/to/vendor/phpstan/phpstan/../../nunomaduro/larastan/bootstrap.php: Undefined index: psr-4
> Script php -d memory_limit=-1 ./vendor/bin/phpstan analyse handling the phpstan event returned with error code 1

My composer.json:
```javascript
{
    ...
    "require": {
        "php": ">=7.4",
        "illuminate/support": ">=4.1.0"
    },
    "autoload": {
        "psr-0": {
            "Flynsarmy\\CsvSeeder\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Flynsarmy\\CsvSeeder\\Tests\\": "tests"
        }
    },
    "minimum-stability": "dev",
    "require-dev": {
        "orchestra/testbench": "5.*",
        "squizlabs/php_codesniffer": "3.*",
        "nunomaduro/larastan": "^0.6.0@dev"
    },
    "scripts": {
        "phpstan": "php -d memory_limit=-1 ./vendor/bin/phpstan analyse"
    }
}
```

My phpstan.neon:
```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
parameters:
    level: 5
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - src
```

Removing the `autoload-dev` section in my composer.json makes no difference even after a `composer dump-autoload`.
