### ISSUE TITLE
\Illuminate\Container\Container::getInstance()->make() and related methods return type not resolved

### ISSUE THREAD

**Issue by gisostallenberg** [nunomaduro/larastan#941]
- Larastan Version: v0.7.12
- `--level` used: 7
- Pull request with failing test: N/A yet

### Description
When using the make method of the container (or through \Illuminate\Foundation\Application) the return type is not resolved.
When using the app helper (or resolve helper which internally uses app) the type is actually resolved (using \NunoMaduro\Larastan\ReturnTypes\Helpers\AppExtension).
Because the `app()` helper, \Illuminate\Foundation\Application and the App facade internally use `\Illuminate\Container\Container::getInstance()->make()` I think it would be better to resolve to the correct type for that make call.

### Laravel code where the issue was found

```php
resolve(MyInterface::class); // phpstan understands this to be an instance of `MyInterface`
app()->make(MyInterface::class); // phpstan does not understand this is an instance of `MyInterface`
```

**Comment by gisostallenberg** [comment]
If you point me in a direction on how this can be changed I'd be happy to make a PR.

**Comment by szepeviktor** [comment]
Hello Giso! Thank you for your report.
We have some tests https://github.com/nunomaduro/larastan/blob/master/tests/Features/ReturnTypes/Helpers/AppExtension.php
although not for `app()->make($class)`.

**Comment by szepeviktor** [comment]
Here it is
https://github.com/nunomaduro/larastan/blob/master/src/ReturnTypes/Helpers/AppExtension.php#L23

**Comment by gisostallenberg** [comment]
Yes, I found out that `app($abstract)` (the same for resolve) works. But these are helpers. How do I start with something that resolves info on specific method calls.

Btw, to quickly make sure app()->make is not used I found this:
https://github.com/spaze/phpstan-disallowed-calls/

With this setting:
```yaml
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
    - ./vendor/spaze/phpstan-disallowed-calls/extension.neon

parameters:
    disallowedMethodCalls:
        -
            method: 'Illuminate\Foundation\Application::make()'
            message: ' you probably used app()->make(), use app(MyService::class) or resolve(MyService::class) instead.'

```
